server:
  port: 8020

spring:
  application:
    name: monitor-service

#turbine:
#  appConfig: user-service,mall-service
#  aggregator:
#    clusterConfig: USER-SERVICE,MALL-SERVICE

turbine:
  aggregator:
    clusterConfig: default
  appConfig: user-service,mall-service
  clusterNameExpression: new String("default")

#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS

eureka:
  instance:
    hostname: monitor-service
    prefer-ip-address: true
    instance-id: monitor-service
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8010/eureka/

