#server:
#  port: 8001
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eservice1:8010/eureka/
#  instance:
#    instance-id: user-service8001
#    prefer-ip-address: true
spring:
  application:
    name: user-service
  jackson:
    serialization:
      write-dates-as-timestamps: true
  profiles:
    active: s1
  boot:
    admin:
      client:
        url: http://localhost:8020
  # sleuth 配置
  sleuth:
#    web:
#      client:
#        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}  # 指定了Zipkin服务器的地址

feign:
  hystrix:
    enabled: true

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

redis:
  lettuce:
    pool:
      max-active: 8 #最大连接数
      max-wait: -1 #默认-1 最大连接阻塞等待时间
      max-idle: 8 #最大空闲连接 默认8
      min-idle: 0 #最小空闲连接
      # 链接超时时间（毫秒）
    timeout: 200
  host: 127.0.0.1
  port: 6379
  password:
  database: 0



datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  initialSize: 0
  maxActive: 200
  minIdle: 1
  maxWait: 60000
  poolPreparedStatements: false
  validationQuery: select 'x'
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 10000
  minEvictableIdleTimeMillis: 86400000
  defaultAutoCommit: true
  maxOpenPreparedStatements: 20
  filters: stat
  url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
  name: root
  password:

mybatis:
    typeAliasesPackage: com.hex.code.user.dao
    mapperLocations: classpath:sqlMappers/*.xml