server:
  port: 8001
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eservice1:8761/eureka/

spring:
  application:
    name: user-service
  jackson:
    serialization:
      write-dates-as-timestamps: true
#
#feign:
#  hystrix:
#    enabled: true
#
## hystrix配置
#hystrix:
#  shareSecurityContext: true
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000


redis:
  lettuce:
    pool:
      max-active: 8 #最大连接数
      max-wait: -1 #默认-1 最大连接阻塞等待时间
      max-idle: 8 #最大空闲连接 默认8
      min-idle: 0 #最小空闲连接
      # 链接超时时间（毫秒）
    timeout: 200
  host: 123.57.84.95
  port: 6379
  password: TFKA(~@!ji^XALQ(sHy7xTwTn8D$s0jF
  database: 3



datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  initialSize: 0
  maxActive: 200
  minIdle: 1
  maxWait: 60000
  poolPreparedStatements: false
  validationQuery: select 'x'
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 10000
  minEvictableIdleTimeMillis: 86400000
  defaultAutoCommit: true
  maxOpenPreparedStatements: 20
  filters: stat
  url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
  name: root
  password:

mybatis:
    typeAliasesPackage: com.hex.code.user.dao
    mapperLocations: classpath:sqlMappers/*.xml